apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../manifests/deployment
- ../../manifests/service
- ../../modules/ingress-istio
images:
- name: inetika/go_test_server
  newTag: 1.0.3


patches:
- patches.yaml

patchesJson6902:
- target:
    group: extensions
    version: v1beta1
    kind: Deployment
    name: deploy
  path: serviceName-patch.yaml
- target:
    version: v1
    kind: Service
    name: svc
  path: serviceName-patch.yaml
- target:
    version: v1
    kind: Service
    name: svc-mesh
  path: serviceName-mesh-patch.yaml
- target:
    group: networking.istio.io
    version: v1alpha3
    kind: DestinationRule
    name: dr
  path: serviceName-mesh-patch.yaml
- target:
    group: networking.istio.io
    version: v1alpha3
    kind: VirtualService
    name: vs
  path: serviceName-patch.yaml
