apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: deploy
spec:
  template:
    metadata:
      name: go-test-server
      labels:
        app: go-test-server
    spec:
      containers:
        - name: go-test-server
---
apiVersion: v1
kind: Service
metadata:
  name: svc-mesh
  labels:
    app: go-test-server
spec:
  selector:
    app: go-test-server
---
apiVersion: v1
kind: Service
metadata:
  name: svc
  labels:
    app: go-test-server
spec:
  selector:
    app: go-test-server
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: vs
spec:
  hosts:
  - "go-test-server.dev2.appetize-dev.com"
  http:
  - match:
    route:
    - destination:
        host: go-test-server-mesh
    - destination:
        host: go-test-server-mesh
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: dr
spec:
  host: go-test-server-mesh
  subsets:
  - name: v1
    labels:
      app: go-test-server
  - name: v2
    labels:
      app: go-test-server

