apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dev2
resources:
- ../../../services/go-test-server2

replicas:
- name: deploy
  count: 1

images:
  - name: inetika/go_test_server
    newTag: 1.0.3

patches:
  - ../patches.yaml
  


