apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: "nginx"
  name: ing
spec:
  rules:
  - host: serverName.dev2.appetize-dev.com
    http:
      paths:
      - backend:
          serviceName: serverName
          servicePort: 80