apiVersion: v1
kind: Service
metadata:
  name: svc
  labels:
    app: serverName
    tier: backend
  annotations:
    # prometheus.io/scrape: "true"
spec:
  selector:
    app: serverName
    tier: backend
    track: stable
  ports:
    - name: http
      port: 80
      targetPort: http-container
      protocol: TCP
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: svc-mesh
  labels:
    app: serverName
    tier: backend
  annotations:
    # prometheus.io/scrape: "true"
spec:
  selector:
    app: serverName
    tier: backend
  ports:
    - name: http
      port: 80
      targetPort: http-container
      protocol: TCP
  type: ClusterIP
