apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../manifests/deployment

commonLabels:
  app: go-test-server
  tier: backend
  track: stable

patches:
  - patches.yaml

patchesJson6902:
    - target:
        group: extensions
        version: v1beta1
        kind: Deployment
        name: deploy
      path: patch-metadataName.yaml

