apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: deploy
spec:
  template:
    metadata:
      name: go-test-server
    spec:
      containers:
      - name: go-test-server2
        image: inetika/go_test_server
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            memory: 250Mi
            cpu: 20m
          limits:
            memory: 1Gi
            cpu: "1"
        ports:
        - containerPort: 80
          name: http-container
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /heartbeat
            port: 80
            scheme: HTTP
          initialDelaySeconds: 15
          periodSeconds: 10
          successThreshold: 6
          timeoutSeconds: 3
        livenessProbe:
          failureThreshold: 2
          httpGet:
            path: /heartbeat
            port: 80
            scheme: HTTP
          initialDelaySeconds: 300
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 3

