apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: "nginx"
  name: ${SERVICE_NAME}-ingress
spec:
  rules:
  - host: ${SERVICE_NAME}.${CUST_DOMAIN}.${TLD}
    http:
      paths:
      - backend:
          serviceName: ${SERVICE_NAME}
          servicePort: 80